vich_uploader:
    db_driver: orm

    mappings:
        image:
            uri_prefix: /uploads/images
            upload_destination: '%images_directory%'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
