language: php
php:
  - '7.4.1'

node_js:
  - 17

before_script:
  # DATABASE_URL=mysql://homestead:secret@127.0.0.1:3306/omm_test?serverVersion=5.7
  # - mysql -u root -e 'CREATE DATABASE omm_test;'
  - mysql -u root -e "CREATE USER 'homestead'@'localhost' IDENTIFIED BY 'secret';"
  - mysql -u root -e "GRANT ALL ON omm_test.* TO 'homestead'@'localhost';"
  - composer install --no-interaction
  - php bin/console doctrine:database:create --env=test
  - php bin/console doctrine:schema:create --env=test
  - php bin/console doctrine:fixtures:load -n --env=test
  - npm install -g yarn
  - yarn run build

before_install:
  - sudo apt-get update
  - sudo apt-get -y install exiftool
  - curl https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-7.12.1-amd64.deb -o elasticsearch.deb
  - sudo dpkg -i --force-confnew elasticsearch.deb
  - sudo chown -R elasticsearch:elasticsearch /etc/default/elasticsearch
  - sudo service elasticsearch restart
  # Elasticsearch can take a while to start
  - sleep 10

env:
  global:
    # Throwaway APP_SECRET, only used on Travis
    - APP_SECRET=baec94fe745a3288a250ab99fa97790b2256ffc1
    # Actual path to exiftool in Travis test environment
    - TEST_EXIFTOOL_PATH=/usr/bin/exiftool

notifications:
  email:
    on_success: always

services:
  - mysql
