language: php
php:
  - '7.4.1'

before_script:
  - composer install --no-interaction

before_install:
  - sudo apt-get update
  - sudo apt-get -y install exiftool

env:
  # Standard build env with throwaway APP_SECRET and the real path to exiftool in test environment
  - APP_SECRET=baec94fe745a3288a250ab99fa97790b2256ffc1 TEST_EXIFTOOL_PATH=/usr/bin/exiftool
