language: php
php:
  - '7.4.1'

before_script:
  - composer install --no-interaction

before_install:
  - sudo apt-get update
  - sudo apt-get -y install exiftool

env:
  global:
    # Throwaway APP_SECRET, only used on Travis
    - APP_SECRET=baec94fe745a3288a250ab99fa97790b2256ffc1
    # Actual path to exiftool in Travis test environment
    - TEST_EXIFTOOL_PATH=/usr/bin/exiftool

notifications:
  email:
    on_success: always
