framework:
    messenger:
        transports:
            # On dev, I want messages to be handled immediately without
            # worrying about queueing.
            # async: 'in-memory://'
            async: 'sync://' # psych!
