monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: grouped
            excluded_http_codes: [404, 405]
            buffer_size: 50 # How many messages should be saved? Prevent memory leaks
        grouped:
            type: group
            members: [logfile, deduplicated]
        logfile:
            type: stream
            include_stacktraces: true
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        deduplicated:
            type: deduplication
            handler: symfony_mailer
        symfony_mailer:
            type:         symfony_mailer
            include_stacktraces: true
            from_email:   'omm-webmaster@gothick.org.uk'
            to_email:     'gothick@gothick.org.uk'
            subject:      'An Error Occurred! %%message%%'
            level:        debug
            formatter:    monolog.formatter.html
            content_type: text/html
        console:
            type: console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
